# Apply complete drop-in replacements

# 1. AudienceSegmentReport.tsx
with open("/Users/damikreddy/Desktop/Hackaton/frontend/src/components/AudienceSegmentReport.tsx", "w", encoding="utf-8") as f:
    f.write('''"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  Users,
  HardHat,
  Briefcase,
  Bike,
  HeartHandshake,
  HeartCrack,
  GraduationCap,
  Store,
  Building2,
  AlertTriangle,
  Sparkles,
  ArrowRight,
  CheckCircle2,
  TrendingUp,
  ChevronDown
} from "lucide-react";

export function AudienceSegmentReport() {
  const [activeSegment, setActiveSegment] = useState<number>(0);
  const [isExpanded, setIsExpanded] = useState<boolean>(true);

  const segments = [
    {
      id: 0,
      title: "Blue-Collar Workers",
      scale: "~35 Million Active",
      icon: HardHat,
      badgeColor: "bg-amber-950/60 text-amber-300 border-amber-800/60",
      problems: [
        "1-character typo rejections between Aadhaar and factory payroll wait 20 days only to be rejected.",
        "Blurry cheque photos on budget phones rejected after 18 days due to illegible IFSC.",
        "Semi-literate workers exploited by cyber cafés charging ₹300–₹500 per form submission.",
        "Merged bank IFSC traps (e.g. Allahabad Bank into Indian Bank) cause immediate claim failures."
      ],
      wishlist: [
        "Voice-first vernacular filing in native dialects (Hindi, Telugu, Tamil, Marathi, Bhojpuri).",
        "Instant client-side photo clarity pre-check before uploading documents.",
        "Sub-2 second emergency medical advances under ₹50,000 via simulated instant UPI/IMPS."
      ],
      solution: "Multilingual Voice Copilot + Canvas Cheque OCR Scanner (<2s) + Levenshtein Fuzzy Matcher (≥85%).",
      route: "/money",
      cta: "Test Instant Emergency Advance"
    },
    {
      id: 1,
      title: "White-Collar & Tech",
      scale: "~28 Million Active",
      icon: Briefcase,
      badgeColor: "bg-blue-950/60 text-blue-300 border-blue-800/60",
      problems: [
        "Previous employer forgets to mark Date of Exit (DOE), disabling Form 13 transfer for months.",
        "Passbook server (passbook.epfindia.gov.in) crashes with 500 errors during peak hours & weekends.",
        "Fragmented Member IDs from 3–4 previous jobs require sequential, slow manual transfers.",
        "Unexpected 10%–20% Section 192A TDS tax deductions on withdrawals over ₹50,000 before 5 continuous years of service."
      ],
      wishlist: [
        "1-Click Multi-Job Consolidation merging all previous Member IDs into active employment.",
        "Sub-50ms visual passbook intelligence with employer/employee share breakdowns.",
        "Automated TDS Shield auto-generating Form 15G if service is under 5 years."
      ],
      solution: "ECR Date Deducer + 1-Click Multi-Merge + Redis Read Cache + Form 15G Auto-Filer.",
      route: "/career",
      cta: "Test 1-Click Multi-Job Merge"
    },
    {
      id: 2,
      title: "Gig & Contract Workers",
      scale: "~7 Million Active",
      icon: Bike,
      badgeColor: "bg-emerald-950/60 text-emerald-300 border-emerald-800/60",
      problems: [
        "Unseeded KYC and inactive UANs generated by aggregators that are never linked to Aadhaar.",
        "PF deducted on salary slips but never deposited by employer (PF theft discovered years later).",
        "Over 80% have no family e-Nomination filed due to Aadhaar OTP timeouts on mobile."
      ],
      wishlist: [
        "Ultra-lightweight mobile experience that runs smoothly on 2G/3G connections.",
        "Employer Compliance Radar (ECR Watchdog) alerting workers on the 16th if deposit is missed.",
        "1-Click mobile e-Nomination with simplified Aadhaar e-Sign."
      ],
      solution: "Sub-50KB Mobile PWA + Employer ECR Non-Compliance Radar + 1-Click Mobile e-Nomination.",
      route: "/savings",
      cta: "View Employer ECR Radar"
    },
    {
      id: 3,
      title: "Retired Senior Pensioners",
      scale: "~7.8 Million EPS-95",
      icon: HeartHandshake,
      badgeColor: "bg-purple-950/60 text-purple-300 border-purple-800/60",
      problems: [
        "November Jeevan Pramaan biometric scanner failures due to tremors or poor mobile lighting.",
        "Unreadable 10px tables and distorted squiggly captchas causing >70% senior login dropouts.",
        "Cryptic bureaucratic statements ('PPO 12(3) ECS Credit') instead of plain payment alerts."
      ],
      wishlist: [
        "Dedicated Senior Mode with 125% font scaling, WCAG AAA 7:1 contrast, and zero captchas.",
        "Voice-Assisted Life Certificate with spoken lighting and eye-blink liveness prompts.",
        "Spoken native voice summaries ('Your ₹4,250 pension was credited on August 1st')."
      ],
      solution: "Senior Citizen Comfort Mode + Voice-Guided Jeevan Pramaan + 56px Touch Ergonomics.",
      route: "/savings",
      cta: "Test Senior Pension & Life Cert"
    },
    {
      id: 4,
      title: "Grieving Families & Widows",
      scale: "~500,000 Claims / Year",
      icon: HeartCrack,
      badgeColor: "bg-rose-950/60 text-rose-300 border-rose-800/60",
      problems: [
        "Forced to navigate 3 separate paper forms (Form 20, 10D, 5IF) during personal grief.",
        "Over 90% unaware of statutory ₹7 Lakh free EDLI life insurance cover at zero premium.",
        "Physical PF office verification demands causing months of delayed survivor relief."
      ],
      wishlist: [
        "Unified 1-Step Bereavement Portal consolidating PF balance, monthly widow pension, and EDLI.",
        "Zero-paper claims auto-fetching Aadhaar death registry records.",
        "Priority emergency disbursement within 48 hours for funeral/medical relief."
      ],
      solution: "Unified Form 5IF+20 Bereavement Hub + Instant ₹7L EDLI Calculator + Digital Beneficiary Verification.",
      route: "/savings",
      cta: "Explore EDLI ₹7L Safety Net"
    },
    {
      id: 5,
      title: "First-Job Entrants & Youth",
      scale: "~2.1 Million / Year",
      icon: GraduationCap,
      badgeColor: "bg-cyan-950/60 text-cyan-300 border-cyan-800/60",
      problems: [
        "Confusing initial UAN activation with alphanumeric password rules and captcha loops.",
        "Forgot password lockout loop forcing 24-hour account suspension and physical branch visit.",
        "Viewing PF as a 12% salary tax rather than an 8.25% sovereign compounding wealth asset."
      ],
      wishlist: [
        "Passkey / Biometric login using device Touch ID / Face ID (zero passwords).",
        "Interactive 8.25% compounding wealth simulator projecting retirement corpus.",
        "Instant WhatsApp monthly passbook credit notification."
      ],
      solution: "Passwordless Passkey Onboarding + Interactive Samriddhi 8.25% Compounding Forecaster.",
      route: "/savings",
      cta: "Simulate 8.25% Wealth Growth"
    },
    {
      id: 6,
      title: "Assisted Operators & CSCs",
      scale: "~300,000 Cyber Cafés",
      icon: Store,
      badgeColor: "bg-teal-950/60 text-teal-300 border-teal-800/60",
      problems: [
        "Mid-form timeouts and session crashes when filing for multiple rural workers on spotty broadband.",
        "Frustrated citizens returning angry after 20 days when claims get rejected for simple typos.",
        "Lack of printable confirmation slips with tamper-evident tracking QR codes."
      ],
      wishlist: [
        "Pre-submission health check guaranteeing 99% approval before hitting submit.",
        "Offline-tolerant form drafts saved locally in browser IndexedDB.",
        "Printable 1-page A4 PDF submission receipts with QR audit hash."
      ],
      solution: "80% Client-Side Pre-Validation Engine + Instant Printable Audit PDF Receipts.",
      route: "/fix",
      cta: "Run Pre-Flight KYC Check"
    },
    {
      id: 7,
      title: "Corporate HR & Payroll",
      scale: "~750,000 Establishments",
      icon: Building2,
      badgeColor: "bg-indigo-950/60 text-indigo-300 border-indigo-800/60",
      problems: [
        "15th-of-the-month ECR server lockouts causing delayed statutory contribution penalties.",
        "Manual 4-page paper Joint Declarations requiring physical signatures and postal couriers.",
        "Digital Signature Certificate (DSC) USB dongle browser Java plugin incompatibilities."
      ],
      wishlist: [
        "3-Way Digital Joint Declaration with automated employer portal approval inbox.",
        "Bulk ECR pre-flight file validator checking member IDs before upload.",
        "Zero-plug-in cryptographic approval using standard OAuth2 and WebAuthn."
      ],
      solution: "Paperless 3-Way Digital Joint Declaration + Automated ECR Validator API.",
      route: "/fix",
      cta: "Test 3-Way Joint Declaration"
    }
  ];

  const current = segments[activeSegment];
  const Icon = current.icon;

  return (
    <section className="w-full bg-gradient-to-br from-slate-900 via-sovereign-darkest to-sovereign-navy rounded-3xl p-6 sm:p-8 border border-slate-700/80 shadow-2xl text-white space-y-6 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-96 h-96 bg-saffron/10 rounded-full blur-3xl pointer-events-none" />

      {/* Section Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-slate-700/80 relative z-10">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-saffron/20 text-saffron">
              <Users className="w-4 h-4" />
            </span>
            <span className="text-[10px] font-bold tracking-wider uppercase text-saffron font-mono">
              Target Audience Problem & Feature Expectation Report
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-white mt-1">
            Comprehensive Target Audience Problem & Expectation Matrix
          </h2>
          <p className="text-xs text-slate-300 max-w-3xl mt-1">
            Detailed breakdown of real-world failure points across 70 million Indian workers and how Jan-EPF AI delivers tailored sovereign solutions.
          </p>
        </div>

        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-bold flex items-center gap-1.5 transition-all text-slate-300 shrink-0 border border-white/10"
        >
          <span>{isExpanded ? "Collapse Report" : "Expand Report"}</span>
          <ChevronDown className={`w-3.5 h-3.5 transition-transform ${isExpanded ? "rotate-180" : ""}`} />
        </button>
      </div>

      {isExpanded && (
        <div className="space-y-6 animate-in fade-in duration-300 relative z-10">
          {/* Segment Selector Tabs (8 Segments Grid) */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-2">
            {segments.map((seg, idx) => {
              const TabIcon = seg.icon;
              const isSelected = activeSegment === idx;
              return (
                <button
                  key={seg.id}
                  onClick={() => setActiveSegment(idx)}
                  className={`p-2.5 rounded-2xl border text-left transition-all flex flex-col justify-between gap-1.5 ${
                    isSelected
                      ? "bg-slate-800 text-white border-saffron/80 shadow-[0_0_15px_rgba(245,158,11,0.2)] ring-1 ring-saffron/50"
                      : "bg-slate-800/70 text-slate-300 border-slate-700/80 hover:border-saffron/50 hover:bg-slate-800"
                  }`}
                >
                  <TabIcon className={`w-4 h-4 ${isSelected ? "text-saffron drop-shadow-[0_0_5px_rgba(245,158,11,0.5)]" : "text-slate-400"}`} />
                  <div>
                    <span className="text-[11px] font-bold block leading-tight truncate">{seg.title}</span>
                    <span className={`text-[9px] font-mono block ${isSelected ? "text-saffron/80" : "text-slate-500"}`}>
                      {seg.scale}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Active Segment Detail Card */}
          <div className="p-6 rounded-2xl bg-slate-800/70 backdrop-blur-md border border-slate-700/80 shadow-lg space-y-5 transition-all">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 pb-3 border-b border-slate-700/80">
              <div className="flex items-center gap-3">
                <div className="w-11 h-11 rounded-2xl bg-white/10 border border-white/10 text-saffron flex items-center justify-center shadow-md">
                  <Icon className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-black text-white flex items-center gap-2">
                    <span>Segment #{current.id + 1}: {current.title}</span>
                    <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-full border ${current.badgeColor}`}>
                      {current.scale}
                    </span>
                  </h3>
                  <p className="text-xs text-slate-300 font-medium mt-0.5">
                    Real-World Pain Points, Feature Wishlist & Jan-EPF AI Architectural Solution
                  </p>
                </div>
              </div>

              <Link
                href={current.route}
                className="px-4 py-2.5 bg-saffron text-sovereign-darkest hover:bg-amber-400 font-extrabold text-xs rounded-xl flex items-center justify-center gap-2 transition-all shadow-md self-stretch sm:self-auto border border-saffron/50"
              >
                <span>{current.cta}</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
              {/* Problem Statement */}
              <div className="bg-rose-950/40 p-4 rounded-2xl border border-rose-900/50 space-y-2">
                <div className="flex items-center gap-1.5 font-extrabold text-rose-300">
                  <AlertTriangle className="w-4 h-4 text-rose-400" />
                  <span>Real Problems & Systemic Bottlenecks Faced Today:</span>
                </div>
                <ul className="space-y-1.5 text-slate-200 font-medium">
                  {current.problems.map((p, i) => (
                    <li key={i} className="flex items-start gap-1.5 leading-relaxed">
                      <span className="text-rose-500 font-bold shrink-0">•</span>
                      <span>{p}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Citizen Wishlist */}
              <div className="bg-blue-950/40 p-4 rounded-2xl border border-blue-900/50 space-y-2">
                <div className="flex items-center gap-1.5 font-extrabold text-blue-300">
                  <Sparkles className="w-4 h-4 text-blue-400" />
                  <span>What They Are Expecting (Citizen Feature Wishlist):</span>
                </div>
                <ul className="space-y-1.5 text-slate-200 font-medium">
                  {current.wishlist.map((w, i) => (
                    <li key={i} className="flex items-start gap-1.5 leading-relaxed">
                      <span className="text-blue-400 font-bold shrink-0">✓</span>
                      <span>{w}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* How Jan-EPF AI Solves It */}
            <div className="bg-emerald-950/40 p-4 rounded-2xl border border-emerald-900/50 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
                <div>
                  <span className="text-[10px] font-bold text-emerald-300 uppercase block">Engineered Solution in Jan-EPF AI</span>
                  <p className="text-xs font-black text-white mt-0.5">{current.solution}</p>
                </div>
              </div>
              <span className="text-[10px] font-bold px-2.5 py-1 bg-emerald-950/60 text-emerald-300 border border-emerald-800/60 rounded-full font-mono shrink-0">
                100% Implemented
              </span>
            </div>
          </div>

          {/* Before vs. After Audience Impact Transformation Scorecard */}
          <div className="bg-slate-800/70 backdrop-blur-md border border-slate-700/80 text-white rounded-3xl p-6 shadow-xl space-y-4">
            <div className="flex items-center gap-2 pb-3 border-b border-slate-700/80">
              <span className="p-1.5 rounded-lg bg-saffron/20 text-saffron">
                <TrendingUp className="w-4 h-4" />
              </span>
              <h3 className="text-base font-extrabold tracking-wide">
                Summary Scorecard: Legacy EPFO vs. Jan-EPF AI Transformation
              </h3>
            </div>

            <div className="overflow-x-auto rounded-2xl border border-slate-700/80">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-900/80 text-slate-300 font-bold border-b border-slate-700/80">
                  <tr>
                    <th className="p-3">Metric / Dimension</th>
                    <th className="p-3 text-rose-400">Legacy EPFO Experience</th>
                    <th className="p-3 text-emerald-400">Jan-EPF AI Experience</th>
                    <th className="p-3 text-right">Architectural Guarantee</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-700/80 text-slate-200 bg-slate-800/30">
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Claim Rejection Rate</td>
                    <td className="p-3 text-rose-300">35% – 40% (Over 3.2M rejections/yr)</td>
                    <td className="p-3 text-emerald-400 font-bold">&lt; 2% (Pre-flight OCR & Fuzzy)</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">Zero Blind Uploads</td>
                  </tr>
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Average Claim Turnaround</td>
                    <td className="p-3 text-rose-300">15 – 25 Days</td>
                    <td className="p-3 text-emerald-400 font-bold">Sub-2 Seconds (Instant DBT)</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">Simulated UPI / IMPS</td>
                  </tr>
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Senior Pensioner Dropouts</td>
                    <td className="p-3 text-rose-300">&gt; 70% on Captchas & Face DLC</td>
                    <td className="p-3 text-emerald-400 font-bold">&lt; 1% (Voice-Assisted Mode)</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">WCAG AAA / No Captcha</td>
                  </tr>
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Multi-Job Transfer Time</td>
                    <td className="p-3 text-rose-300">3 – 6 Months (Manual HR exit dates)</td>
                    <td className="p-3 text-emerald-400 font-bold">1-Click Instant Consolidation</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">ECR Date Deduction</td>
                  </tr>
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Joint Declaration Speed</td>
                    <td className="p-3 text-rose-300">6 – 12 Months (Paper courier loops)</td>
                    <td className="p-3 text-emerald-400 font-bold">&lt; 24 Hours (Digital 3-Way)</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">Paperless Handshake</td>
                  </tr>
                  <tr className="hover:bg-slate-700/40 transition-colors">
                    <td className="p-3 font-semibold text-white">Server Availability</td>
                    <td className="p-3 text-rose-300">Frequent 500 crashes on peak days</td>
                    <td className="p-3 text-emerald-400 font-bold">100% Continuous Uptime</td>
                    <td className="p-3 text-right font-mono text-xs text-saffron">6 Hot Substitutes</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
''')
print("Wrote AudienceSegmentReport.tsx successfully!")

# 2. CitizenFeatureMatrix.tsx
with open("/Users/damikreddy/Desktop/Hackaton/frontend/src/components/CitizenFeatureMatrix.tsx", "w", encoding="utf-8") as f:
    f.write('''"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  Zap,
  Activity,
  Radar,
  GitMerge,
  ShieldAlert,
  HeartHandshake,
  FileCheck2,
  Users,
  ChevronDown,
  Sparkles,
  ArrowRight
} from "lucide-react";

export function CitizenFeatureMatrix() {
  const [isOpen, setIsOpen] = useState<boolean>(true);

  const features = [
    {
      id: "1",
      title: "1. Instant UPI Advance",
      tagline: "Sub-2s Emergency Payout",
      description: "Auto-settles emergency medical advances under ₹50,000 in seconds via simulated instant UPI/IMPS. Replaces 7–20 day clerical delays.",
      route: "/money",
      cta: "Test Instant Payout",
      icon: Zap,
      badge: "EPFO 3.0 Standard",
      badgeColor: "bg-emerald-950/60 text-emerald-300 border-emerald-800/60",
      accent: "hover:border-emerald-500/50"
    },
    {
      id: "2",
      title: "2. Claim Health Score (99%)",
      tagline: "Pre-Flight Rejection Diagnostic",
      description: "Pre-validates Name Match (Levenshtein ≥85%), Bank KYC, and Canvas Cheque readability BEFORE submission to guarantee zero rejections.",
      route: "/money",
      cta: "Run Diagnostic",
      icon: Activity,
      badge: "Zero-Rejection Shield",
      badgeColor: "bg-blue-950/60 text-blue-300 border-blue-800/60",
      accent: "hover:border-blue-500/50"
    },
    {
      id: "3",
      title: "3. Employer ECR Radar",
      tagline: "'PF Theft Alert' Watchdog",
      description: "Monitors monthly salary deductions against EPFO ECR challans. Alerts the worker on the 16th if the company deducted PF but failed to deposit.",
      route: "/savings",
      cta: "View Deposit Watchdog",
      icon: Radar,
      badge: "Statutory Compliance",
      badgeColor: "bg-rose-950/60 text-rose-300 border-rose-800/60",
      accent: "hover:border-rose-500/50"
    },
    {
      id: "4",
      title: "4. 1-Click Multi-Merge",
      tagline: "Universal Account Consolidation",
      description: "Consolidates 3–4 past Member IDs into active employment in 1 tap. Auto-deduces missing Date of Exit from last ECR wage timestamp.",
      route: "/career",
      cta: "Merge Accounts",
      icon: GitMerge,
      badge: "Form 13 Auto-Merge",
      badgeColor: "bg-purple-950/60 text-purple-300 border-purple-800/60",
      accent: "hover:border-purple-500/50"
    },
    {
      id: "5",
      title: "5. Automated TDS Shield",
      tagline: "Form 15G 1-Click Auto-Filer",
      description: "Detects service < 5 years and auto-generates Form 15G with 1 tap, shielding workers from surprise 10%–20% Section 192A TDS deductions on withdrawals over ₹50,000.",
      route: "/career",
      cta: "Check TDS Exemption",
      icon: ShieldAlert,
      badge: "Tax Protection",
      badgeColor: "bg-amber-950/60 text-amber-300 border-amber-800/60",
      accent: "hover:border-amber-500/50"
    },
    {
      id: "6",
      title: "6. Senior Voice Life Cert.",
      tagline: "Guided Jeevan Pramaan Face RD",
      description: "Voice-assisted facial biometric capture with gentle spoken cues ('Please blink your eyes now, Gurmeet ji') and Elder Comfort mode.",
      route: "/savings",
      cta: "Renew Life Certificate",
      icon: HeartHandshake,
      badge: "EPS-95 Pension",
      badgeColor: "bg-orange-950/60 text-orange-300 border-orange-800/60",
      accent: "hover:border-orange-500/50"
    },
    {
      id: "7",
      title: "7. Zero-Paper Joint Decl.",
      tagline: "Digital 3-Way Cryptographic Handshake",
      description: "Correct name, DOB, and father's name without printing 4-page forms or physical visits. Instant Citizen e-Sign <-> Employer <-> EPFO RO.",
      route: "/fix",
      cta: "Submit Digital Joint Decl.",
      icon: FileCheck2,
      badge: "Zero Paperwork",
      badgeColor: "bg-teal-950/60 text-teal-300 border-teal-800/60",
      accent: "hover:border-teal-500/50"
    },
    {
      id: "8",
      title: "8. AI Grievance Copilot",
      tagline: "Automated Error-Code Root Cause",
      description: "Paste delayed claim complaints in plain Hindi/English. The AI diagnoses the exact root cause and submits a prioritized resolution draft.",
      route: "/fix",
      cta: "Diagnose Delay",
      icon: Users,
      badge: "EPFiGMS Modernization",
      badgeColor: "bg-indigo-950/60 text-indigo-300 border-indigo-800/60",
      accent: "hover:border-indigo-500/50"
    }
  ];

  return (
    <section className="w-full bg-gradient-to-br from-slate-900 via-sovereign-darkest to-sovereign-navy rounded-3xl p-6 sm:p-8 border border-slate-700/80 shadow-2xl text-white space-y-6 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-96 h-96 bg-saffron/10 rounded-full blur-3xl pointer-events-none" />

      {/* Section Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-4 border-b border-slate-700/80 relative z-10">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 border border-white/10 text-white text-[10px] font-mono tracking-wider font-bold shadow-sm uppercase">
            <Sparkles className="w-3.5 h-3.5 text-saffron" />
            <span>Solving Real Citizen Pain Points • EPFO 3.0 Transformation</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-extrabold text-white mt-2">
            The 8 High-Demand Real-World Features Matrix
          </h2>
          <p className="text-xs text-slate-300 max-w-3xl mt-1">
            Derived directly from public grievances and community audits. Every statutory roadblock is solved on-device with zero-trust sovereign architecture.
          </p>
        </div>

        <button
          onClick={() => setIsOpen(!isOpen)}
          className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-bold flex items-center gap-1.5 transition-all text-slate-300 shrink-0 border border-white/10"
        >
          <span>{isOpen ? "Collapse Matrix" : "Expand Matrix"}</span>
          <ChevronDown className={`w-3.5 h-3.5 transition-transform ${isOpen ? "rotate-180" : ""}`} />
        </button>
      </div>

      {/* 8 Feature Cards Grid */}
      {isOpen && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 relative z-10 animate-in fade-in duration-300">
          {features.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.id}
                className={`p-5 rounded-2xl bg-slate-800/70 backdrop-blur-md border border-slate-700/80 transition-all shadow-lg flex flex-col justify-between group overflow-hidden ${f.accent}`}
              >
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <div className="w-10 h-10 rounded-xl bg-white/10 border border-white/10 text-saffron flex items-center justify-center font-bold group-hover:scale-105 transition-transform">
                      <Icon className="w-5 h-5" />
                    </div>
                    <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full border font-mono ${f.badgeColor}`}>
                      {f.badge}
                    </span>
                  </div>

                  <div>
                    <h3 className="text-sm font-extrabold text-white group-hover:text-saffron transition-colors leading-snug">{f.title}</h3>
                    <p className="text-[11px] font-bold text-slate-400 mt-0.5">{f.tagline}</p>
                  </div>

                  <p className="text-xs text-slate-300 leading-relaxed pb-2">
                    {f.description}
                  </p>
                </div>

                <div className="pt-2 border-t border-slate-700/60 mt-2">
                  <Link
                    href={f.route}
                    className="w-full py-2.5 px-3 bg-saffron text-sovereign-darkest hover:bg-amber-400 text-xs font-extrabold rounded-xl flex items-center justify-between transition-all shadow-md group-hover:shadow-[0_0_10px_rgba(245,158,11,0.3)]"
                  >
                    <span>{f.cta}</span>
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                  </Link>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
''')
print("Wrote CitizenFeatureMatrix.tsx successfully!")

# 3. SreTelemetryPanel.tsx
with open("/Users/damikreddy/Desktop/Hackaton/frontend/src/components/SreTelemetryPanel.tsx", "w", encoding="utf-8") as f:
    f.write('''"use client";

import React, { useState } from "react";
import {
  Activity,
  Cpu,
  ShieldCheck,
  Zap,
  CheckCircle2,
  ChevronDown,
  Terminal,
  Database,
  Lock,
  Radio
} from "lucide-react";
import { LiveSreNetworkPulse } from "@/components/LiveSreNetworkPulse";
import { PresidioPlayground } from "@/components/PresidioPlayground";

export function SreTelemetryPanel() {
  const [isOpen, setIsOpen] = useState<boolean>(true);
  const [activeSubTab, setActiveSubTab] = useState<"pulse" | "presidio" | "metrics">("pulse");

  const metrics = [
    {
      label: "80/20 Sovereign Engine",
      value: "82.4% On-Device",
      sub: "$0 API Cloud Bill • Sub-5ms Execution",
      status: "OPTIMAL",
      icon: Cpu,
      color: "text-emerald-300 border-emerald-800/60 bg-emerald-950/60"
    },
    {
      label: "Zero-Trust Presidio Shield",
      value: "100% PII Masked",
      sub: "Aadhaar / PAN Tokenized • DPDP Act 2023",
      status: "ACTIVE",
      icon: ShieldCheck,
      color: "text-blue-300 border-blue-800/60 bg-blue-950/60"
    },
    {
      label: "Substitute SRE Resilience",
      value: "6 / 6 Circuits Healthy",
      sub: "WASM OCR • Web Speech • Offline IndexedDB",
      status: "CANARY VERIFIED",
      icon: Zap,
      color: "text-amber-300 border-amber-800/60 bg-amber-950/60"
    },
    {
      label: "PostgreSQL Row-Level Security",
      value: "Tenant Isolated",
      sub: "RLS Policies Enforced • 0% Cross-Tenant Leak",
      status: "ENFORCED",
      icon: Database,
      color: "text-purple-300 border-purple-800/60 bg-purple-950/60"
    }
  ];

  return (
    <section className="w-full bg-gradient-to-br from-slate-900 via-sovereign-darkest to-sovereign-navy rounded-3xl p-6 sm:p-8 border border-slate-700/80 shadow-2xl text-white space-y-6 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-96 h-96 bg-saffron/10 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 relative z-10 border-b border-slate-700/80 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-11 h-11 rounded-2xl bg-white/10 border border-white/10 text-emerald-400 flex items-center justify-center shadow-md">
            <Activity className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-mono font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping inline-block" />
                Live SRE Telemetry &amp; Resilience Monitor
              </span>
            </div>
            <h3 className="text-xl sm:text-2xl font-extrabold text-white mt-1">
              Sovereign Operational Health, Azure Ping &amp; DPDP Compliance
            </h3>
          </div>
        </div>

        <div className="flex items-center gap-3 mt-2 sm:mt-0">
          {/* Sub-tab Switchers */}
          <div className="flex items-center bg-slate-800/70 p-1 rounded-xl border border-slate-700/80 text-xs shadow-inner">
            <button
              onClick={() => setActiveSubTab("pulse")}
              className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                activeSubTab === "pulse"
                  ? "bg-emerald-950/60 text-emerald-300 border border-emerald-800/60 shadow-sm"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              ⚡ Live Azure Pulse
            </button>
            <button
              onClick={() => setActiveSubTab("presidio")}
              className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                activeSubTab === "presidio"
                  ? "bg-blue-950/60 text-blue-300 border border-blue-800/60 shadow-sm"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              🛡️ Presidio DPDP Sandbox
            </button>
            <button
              onClick={() => setActiveSubTab("metrics")}
              className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                activeSubTab === "metrics"
                  ? "bg-slate-700 text-white border border-slate-600 shadow-sm"
                  : "text-slate-400 hover:text-white"
              }`}
            >
              📊 Core Signals
            </button>
          </div>

          <button
            onClick={() => setIsOpen(!isOpen)}
            className="p-2 rounded-xl bg-white/10 hover:bg-white/20 border border-white/10 text-slate-300 transition-all shrink-0"
            title="Toggle Panel"
          >
            <ChevronDown className={`w-4 h-4 transition-transform ${isOpen ? "rotate-180" : ""}`} />
          </button>
        </div>
      </div>

      {isOpen && (
        <div className="space-y-4 animate-in fade-in duration-300 relative z-10">
          {activeSubTab === "pulse" && <LiveSreNetworkPulse />}

          {activeSubTab === "presidio" && <PresidioPlayground />}

          {activeSubTab === "metrics" && (
            <div className="space-y-5">
              {/* Metrics Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {metrics.map((m, idx) => {
                  const Icon = m.icon;
                  return (
                    <div
                      key={idx}
                      className="bg-slate-800/70 backdrop-blur-md border border-slate-700/80 rounded-2xl p-5 flex flex-col justify-between space-y-3 hover:border-saffron/50 transition-colors shadow-lg group relative overflow-hidden"
                    >
                      <div className="flex justify-between items-start">
                        <span className="text-xs text-slate-300 font-semibold">{m.label}</span>
                        <span className={`text-[9px] font-mono font-bold px-2.5 py-0.5 rounded-full border ${m.color}`}>
                          {m.status}
                        </span>
                      </div>

                      <div>
                        <div className="text-xl font-extrabold font-mono text-white tracking-tight">
                          {m.value}
                        </div>
                        <p className="text-[11px] text-slate-400 mt-1 font-sans">
                          {m.sub}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* SRE Canary Pipeline Verification Banner */}
              <div className="p-4 rounded-2xl bg-slate-800/70 backdrop-blur-md border border-slate-700/80 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 text-xs shadow-lg">
                <div className="flex items-center gap-3 text-slate-300">
                  <div className="p-1.5 rounded-lg bg-saffron/20 text-saffron">
                    <Terminal className="w-4 h-4 shrink-0" />
                  </div>
                  <span>
                    <strong className="text-white">CI/CD SRE Canary Watchdog:</strong> 5-Stage Automated Probe Suite verified on GitHub Actions with auto-retry canary loops.
                  </span>
                </div>
                <span className="text-[10px] font-mono font-bold text-emerald-300 bg-emerald-950/60 px-3 py-1 rounded-full border border-emerald-800/60 shrink-0 flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5" /> Zero Outage SLA
                </span>
              </div>
            </div>
          )}
        </div>
      )}
    </section>
  );
}
''')
print("Wrote SreTelemetryPanel.tsx successfully!")
